### ISSUE TITLE
Mod doesn't work? - NullReferenceException

### ISSUE THREAD

**Issue by wCATw** [Commander-Cat101/ContentSettings#21]
I don't understand if your mod is working incorrectly or if there is a problem with other mods.
[LogOutput.log](https://github.com/user-attachments/files/16582483/LogOutput.log)
![error](https://github.com/user-attachments/assets/ea1d8ed5-b35c-4fe2-b412-bfce0eaff3b0)
![error](https://github.com/user-attachments/assets/def0f569-9aa7-4ad0-9051-85d756712b0d)

**Comment by RedstoneWizard08** [comment]
@wCATw this has been fixed in ConfigurableWarning. ConfigurableWarning is ContentSettings' drop-in replacement and is compatible with everything that uses ContentSettings, as long as you remove ContentSettings.

https://thunderstore.io/c/content-warning/p/RedstoneWizard08/ConfigurableWarning/

**Comment by ellamoon555** [comment]
@RedstoneWizard08 I still get this issue with that mod, and I get stuck on the connecting screen

**Comment by RedstoneWizard08** [comment]
Okay. I'll take a look tomorrow.
Mind sharing a list of the mods you're using?

**Comment by ellamoon555** [comment]
@RedstoneWizard08 Yep here you go

BepInExPack v5.4.2100 by BepInEx

MoreColors v1.5.1 by ViViKo

Virality v1.5.3 by MaxWasUnavailable

Official_BepInExConfigurationManager v18.3.0 by Azumatt

MakeMeRagdoll v1.1.2 by RamuneNeptune

BetterOxygen v1.3.1 by SmileHappyMods

MoreSettings v0.2.0 by Jasson9

Toggle_Mute v1.0.0 by Computery

ViewRollover v1.0.2 by Electric131

MoreSpookerVideo v1.0.7 by TrioGhost

DetourContext_Dispose_Fix v1.0.3 by Hamunii

AutoHookGenPatcher v1.0.4 by Hamunii

DealReroll v1.0.0 by cyclozarin

DealCancel v1.0.1 by cyclozarin

GadgetTweaks v1.2.0 by ViViKo

FixItemSpawn v1.0.0 by Electric131

Freecam v1.1.7 by EpicRaisin

VolumeBooster v1.0.10 by RamuneNeptune

Diving_Bell_Tweaks v1.1.1 by Froj

Free_Healthcare v1.0.1 by Froj

Any_Sprint_Direction v1.0.0 by Uprank

EmoteWheel v1.0.0 by Playboi

MoReOxygen v1.0.1 by JustMeForNow

HostIsBoss v1.0.0 by Doomby

CameraON v1.0.3 by StupidRepo

MyceliumNetworking v1.0.14 by RugbugRedfern

ConfigurableWarning v1.15.2

**Comment by RedstoneWizard08** [comment]
Thanks, I'll have a look later today hopefully. I'm working on a pretty big update anyway, so there's a good chance it's already been fixed.

**Comment by ellamoon555** [comment]
@ RedstoneWizard08 Do you have any idea when you will release this update? even just a loose estimate would be nice :)

**Comment by RedstoneWizard08** [comment]
Hi, sorry, I've been extremely busy with a combo of homework and another project. Unfortunately I can't give an estimate, sorry. I'll do it as soon as I can.

**Comment by ellamoon555** [comment]
No worries!

**Comment by RedstoneWizard08** [comment]
Well, it looks like we'll need to figure out which mod the `RegionSwitcher` comes from. I'll have to do a bit of testing.
